### ISSUE TITLE
Apply rules by HTML content

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#58] opened 2023-04-30 02:02 UTC
### Feature Request

I am trying to create a custom rule for Xenforo sites, but there is no common URL pattern that I can use (and applying it to everything seems to prevent other custom rules from running on sites that match).

I did notice that all Xenforo sites appear to have `<html id="XF"` right next to the beginning, and I was wondering if it will be possible to allow filtering by HTML content, since infy has to scan it anyway to find the elements.

**Comment by MurkBRA** [comment] 2023-05-17 14:10
Why not just filter the id XF on XPath? Like this:
"clickElement": "id('XF')//nav/button[@aria-current='true']/following-sibling::a[not(@hidden)]",
"loadElement": "id('XF')//section//div/ul//figure",
"pageElement": "id('XF')//section/div/ul | id('XF')//section/div/div/ul | id('XF')//section/div/div/div/ul",

Then set the URL to any in regexp (.*)
No needs enhancement

**Comment by sixcious** [comment] 2023-05-17 20:26
Hi,

I wanted to wait until 0.8 was officially out before replying to this to avoid confusion. Most users are still on 0.7 and only a few people are using the 0.8 pre-release.

Technically, yes, in 0.8, you will be able to filter by the action/append mode paths, so you could start your nextLink or pageElement path with an XPath expression like `html[@id='XF']/` and it will only activate on those sites.

The issue is that in 0.7 it's designed to only look at the URL pattern, and it will "activate" on the first one it finds. This is due to #42, so I added the enhancement tag to this issue as well.

Note: When saving multiple generic URL patterns, you need to make sure that they are all unique. So instead of `.*`, save it as something with extra optional text like `.*[Xenforo]?`.

I'll close this when 0.8 is on the web stores (which will hopefully be soon).

Thanks.

**Comment by alexolog** [comment] 2023-05-17 20:37
> Why not just filter the id XF on XPath? Like this: "clickElement": "id('XF')//nav/button[@aria-current='true']/following-sibling::a[not(@hidden)]", "loadElement": "id('XF')//section//div/ul//figure", "pageElement": "id('XF')//section/div/ul | id('XF')//section/div/div/ul | id('XF')//section/div/div/div/ul",
> 
> Then set the URL to any in regexp (.*) No needs enhancement

I do not see any of clickElement, loadElement, pageElement in infy rules.

**Comment by alexolog** [comment] 2023-05-17 21:18
> Hi,
> 
> I wanted to wait until 0.8 was officially out before replying to this to avoid confusion. Most users are still on 0.7 and only a few people are using the 0.8 pre-release.
> 
> Technically, yes, in 0.8, you will be able to filter by the action/append mode paths, so you could start your nextLink or pageElement path with an XPath expression like `html[@id='XF']/` and it will only activate on those sites.
> 
> The issue is that in 0.7 it's designed to only look at the URL pattern, and it will "activate" on the first one it finds. This is due to #42, so I added the enhancement tag to this issue as well.
> 
> Note: When saving multiple generic URL patterns, you need to make sure that they are all unique. So instead of `.*`, save it as something with extra optional text like `.*[Xenforo]?`.
> 
> I'll close this when 0.8 is on the web stores (which will hopefully be soon).
> 
> Thanks.

Ideally, it would first try to match the URL, then check if both the page element and the next rule, and if not, continue to the next rule that matches the URL

Also, are there plans to unify the database and the saves?

**Closed** 2023-05-30 21:08 UTC
Labels: enhancement
