### ISSUE TITLE
Enhanced Firefox Shortcuts and System Default Icon Support

### ISSUE THREAD

**Issue by wordpure** [sixcious/infy-scroll#55] opened 2023-03-08 15:16 UTC
### Feature Request

1. Add a shortcut to activate toolbar buttons for Firefox.
	Activating the toolbar button is a common action, but Firefox doesn't offer custom shortcuts after installing extensions like Chrome does. 

	I hope to achieve an effect similar to the figure below through [_execute_browser_action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#special_shortcuts).

	![图片](https://user-images.githubusercontent.com/68013962/223744168-7d6a54dd-a24f-456d-95e0-cc7670f8a4e2.png)

2. Support for modifying extension shortcuts in the settings page.
	Currently, the steps for modifying extension shortcuts are cumbersome.
	
	![图片](https://user-images.githubusercontent.com/68013962/223750183-97b38074-ced2-463a-8bf1-92e04691b474.png)	

	I hope to achieve an effect similar to the figure below through [commands.update()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/update) and [commands.reset()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/reset).
	
	![图片](https://user-images.githubusercontent.com/68013962/223750081-67355dd2-46ac-42f4-8b45-918a40ab8731.png)

**Comment by wordpure** [comment] 2023-03-08 15:34
By the way, can toolbar icons support system themes?

![图片](https://user-images.githubusercontent.com/68013962/223757111-6a076c8f-5a5b-4f86-99c4-3ce1684b57b5.png)

**Comment by sixcious** [comment] 2023-03-12 03:44
Hi wordpure, thank you for this feature request!

1 - Maybe one could request in Bugzilla that Firefox add the `_execute_browser_action` shortcut as a default to match Chrome/Edge? I know some of the popular extensions have already done this, but it would honestly be a much better overall solution than making every single developer who ports to Firefox write extra Firefox-specific code. I'll consider this though.

2 - Unfortunately, that's because Firefox doesn't offer a way to programmatically open its Shortcuts page like Chrome does via `chrome://extensions/shortcuts`. This is actually a long-standing feature request on Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1538451

3 - Yes, but not in a clean way (IMO). This is one reason why I let you manually change the icon in the Options. The issue is that there isn't a good place to attach a `prefers-color-scheme` change listener without doing weird things like putting it in the injected content script.  I think a new browser-provided API/listener would be the cleanest solution. The browser vendors (Chrome and Firefox) are actually discussing how to solve this very same problem, so hopefully there will be a solution soon:
https://github.com/w3c/webextensions/issues/229

**Comment by wordpure** [comment] 2023-03-19 06:19
Thanks for trying out these feature requests🌹.

For the first point, I've filed a new pull request on Mozilla Connect in hopes of improving it.

[Add a shortcut key to activate the toolbar button ... - Mozilla Connect](https://connect.mozilla.org/t5/ideas/add-a-shortcut-key-to-activate-the-toolbar-button-by-default-for/idi-p/27269)

For the third point, can you add a more generic extension icon?

Currently, extensions must choose between a dark icon and a light icon, but it does not support automatic switching with browser themes. For me, who is used to the browser theme following the system, I have to manually switch the icon in the extension settings after the browser theme is changed.

It would be nice if there was an option in the settings to have an icon that works in both dark and light modes.

![image](https://user-images.githubusercontent.com/68013962/226157160-aaec28f7-1277-4ba8-a62e-0b3c096bbb3f.png)

PS: The icon used by Default is [icon.png](https://github.com/sixcious/infy-scroll/blob/main/src/base/img/icon.png) in the img directory.

**Comment by sixcious** [comment] 2023-03-21 04:36
Hi again wordpure!

Thanks for creating that post on Mozilla Connect! I gave you a thumbs up 👍 

I've uploaded a new version on GitHub that has a couple of your feature requests implemented:
https://github.com/sixcious/infy-scroll#installation

- I added the `_execute_browser_action` shortcut since it was a one line change in the `manifest.json`. I'll probably forget to do this for my other apps/extensions, so I hope Mozilla implements it as a default shortcut regardless.

- I went ahead and added a new `System` Icon as an option (using the content script workaround).

Feel free to try it out and let me know how the `System` icon works for you. I don't use a theme that changes dynamically, so I hope it works well enough for you. If not, I'll look into adding `icon.png` as an option as you suggested.

Thanks again.

**Comment by wordpure** [comment] 2023-03-21 14:52
Thanks for your update and support for my post🌹.

The shortcut and System Icon work fine on my Firefox.

But I found a small problem: the label tag that wraps the System Icon, its [for attribute](https://github.com/sixcious/infy-scroll/blob/d26124079cd8c6917d6af1e7d93b18846cc69fec/src/base/html/options.html#LL201C34-L201C39) actually uses the Dark Icon, so clicking will only switch to the Dark Icon.

![图片](https://user-images.githubusercontent.com/68013962/226643767-85489820-cc3d-4786-ad7c-dbd94301ca20.png)

**Comment by sixcious** [comment] 2023-07-01 03:58
Ah, I caught that one right around the time you posted. I tend to click on the radio inputs directly myself (since not everyone bothers to wrap `for` labels around the inputs!) so I didn't notice it immediately. Anyhow, this should be fixed in Version 8. I'm going to go ahead and close this out as I think I've addressed everything you brought up. For 2, we'll need to wait for Firefox to address the Bugzilla issue and add a way to link to their UI, like Chrome and Edge have done.

Thanks wordpure! 💜

**Closed by sixcious** 2023-07-01 03:58 UTC
Labels: enhancement
