### ISSUE TITLE
Max 7 pages on Amazon

### ISSUE THREAD

**Issue by rpbp58** [sixcious/infy-scroll#51] opened 2023-01-22 18:47 UTC
Recently Infy Scroll will always stop at 7 pages on Amazon, even when I explicitly request Auto mode.  It always stopped at 7 pages by default, but used to go beyond that when I invoked Auto mode.

Also, where is the 7 page limit set for normal scroll mode?  Can I change it?

**Comment by sixcious** [comment] 2023-01-23 03:56
Hi rpbp58,

Thanks for opening this issue.

I just checked and Amazon themselves seem to be limiting a lot of their search terms to a max of 7 pages. Some do go past 7 though. For example, searching for "toys" only gives me 7 pages, whereas searching for "infinity" gives more than 7 pages.

Can you  provide an example URL containing the search term you're using on Amazon that is limiting you to 7 pages so I can try and reproduce what you're experiencing? Also, what browser and browser version and Infy Scroll version are you using?

To answer your question, there isn't a 7 page limit hardcoded anywhere. Have you tried using it on any other website besides Amazon and also experienced a 7 page limit?

**Comment by alexolog** [comment] 2023-01-23 04:46
I noticed that changing the ordering on amazon to sort by price breaks the paging

**Comment by sixcious** [comment] 2023-02-26 18:35
Yes Alex, that's an example of Amazon behaving like an SPA that changes its page content dynamically and is a similar problem to what you reported in https://github.com/sixcious/infy-scroll/issues/34. In Version 0.8, with the [Navigation API](https://developer.mozilla.org/docs/Web/API/Navigation_API) listener added (or with the Late Activation/Mutation Observer setting on for Firefox), it should detect the change when you change the sort order and then it will deactivate and then re-activate itself based on the newly sorted content.

Anyway, I'm going to go ahead and close this since the original problem seems to be a limitation from Amazon's end, but feel free to reply if you'd like to.

**Closed by sixcious** 2023-02-26 18:35 UTC
Labels: question
