### ISSUE TITLE
DB rules not invoked on some pages

### ISSUE THREAD

**Issue by alexolog** [sixcious/infy-scroll#35] opened 2022-09-23 15:50 UTC
**Describe the bug**
A page that has an associated DB rule is not automatically processed.

1. I go to https://xenforo.com/community/threads/job-xf-emailunsubscribe-invalid-header-value-detected.177611/

2. The next page is not fetched.

3. I click on the extension icon and get the following:

![image](https://user-images.githubusercontent.com/2112513/192000109-eede1a16-7da3-4dfb-a09f-1a99a5274ef8.png)

4. I click [OK] and [ACCEPT]

5. The next page is fetched

6. I refresh the page with [F5]

7. I'm back to step 2.

**Expected behaviour:**
If the page is in the DB, the associated rule should be automatically invoked.

**Website**
https://xenforo.com/community/threads/job-xf-emailunsubscribe-invalid-header-value-detected.177611/

**Environment**
 - Device: PC
 - OS: Windows 10
 - Browser: FF 105.0b9
 - Extension Version: 0.7

**Screenshots**
See above, and also:

![image](https://user-images.githubusercontent.com/2112513/192001408-fb119230-5b9a-4399-80df-8b3c9f2eebd7.png)

**Comment by sixcious** [comment] 2022-09-24 18:30
Hi Alex,

Based on your screenshots, this is the expected behavior. That xenforo website is using the Database URL `^https?://.+` rule, and you have it in your Blacklist, so it won't auto-activate. However, I have a solution to your problem: If you'd like Infy to auto-activate on that website, click the Heart button to add it to your Saved URLs (giving it a good URL pattern/regex). This will allow you to still blacklist the generic database URL pattern, but make an exception for the xenforo website, since it's a Saved URL.

Hope this helps!

**Comment by alexolog** [comment] 2022-09-24 23:59
I beg to disagree.  This is not an expected behaviour since it does not provide sufficient information.  If the rule is in a blacklisted pattern, the message should say so, or at least indicate that activating it would be temporary.

**Comment by sixcious** [comment] 2022-09-25 16:00
In the next version update, there will be an icon in the Popup UI that indicates whether a Database URL is currently blacklisted or whitelisted. I hope that helps. I'm going to go ahead and close this.

**Closed by sixcious** 2022-09-25 16:00 UTC
Labels: question
