### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by RayCist1608** [sixcious/infy-scroll#56] opened 2023-04-21 07:37 UTC
### Issue

I swear, the action.js file is considered as a virus. Microsoft Defender will block it and prevent installation in the browser. I simply renamed it to NotAction.js and changed the manifest but some other users wouldn't get to do it. I've also tried checking the contents of the file on a virtual machine and it was fine...

### Version

0.8

### Browser

Edge 112

### OS

Windows

### Device

PC

**Comment by sixcious** [comment] 2023-04-22 19:32
Hi,

I can't reproduce this on my Windows PC. This repository gets cloned by users pretty regularly and no one else has complained about this before. Also, I went ahead and did a custom Defender scan on the `src/base/js` folder and it returned ***0 threats found*** found for all 32 .js files scanned, including `action.js`:

![custom-scan](https://user-images.githubusercontent.com/1027814/233802018-c82f3d87-205e-4541-8c58-8f9f86238574.png)

You might want to look at your Defender configuration settings or [report this as a false positive to Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission). Microsoft has been known to detect [JavaScript files as false positives in the past](https://answers.microsoft.com/en-us/windows/forum/all/windows-defender-bug-detects-javascript-files-as/c8a2c595-6a54-4b2e-a0b5-6aa0f8f536a3).

I'm going to go ahead and close this, but feel free to reply if you'd like to.

**Closed by sixcious** 2023-04-22 19:32 UTC
Labels: question
