### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by eduardorandom** [sixcious/infy-scroll#75] opened 2023-10-25 04:47 UTC
### Problem

I tested your plugin and noticed that I can't save anything. Thought it was Ublock since they all have it but couldn't be since it is an extension, not a site.

### URL

https://download.cnet.com/windows/3/?sort=mostPopular

### Version

0.8 for each i beleive

### Browser

Brave  v1.59.122, Edge 118.0.2088.6, Firefox 119

### OS

Windows 11

### Device

PC

**Comment by sixcious** [comment] 2023-10-26 02:43
Hi, thank you for opening this issue and for using Infy!

I've updated the Help Guide to better document how to add a save [here](https://github.com/sixcious/infy-scroll/wiki/Saves#adding-saves).

There's two ways to add a save in the app:
1. From the Popup UI Window
2. From the Options Screen

I'm assuming you're using the Popup UI Window. If so, you need to click the Heart Button in the top-right corner to bring up the Save Dialog, then enter the URL Pattern and click the `YES` Button (so that the heart is now filled in), and then click the `ACCEPT` Button. Afterwards, you should see a purple heart icon in the top-right corner like this:

<img src="https://github.com/sixcious/infy-scroll/assets/1027814/d0d8a269-38f6-437b-a57c-c50c5863e05b" height="150">

If you're not seeing the purple heart icon as shown above, can you please describe the exact steps you are doing so I can try and reproduce the issue?

I hope this helps! 💜

**Comment by eduardorandom** [comment] 2023-10-26 04:12
Here is a video I recorded on a Firefox browser. The only active extension is yours, ublock for ads, and a screen recorder to record it. Other extensions are disabled.
https://www.veed.io/view/0ac5ae9b-17a6-41da-8d9c-cf88587b7ba3
(In case you can't see it, lmk)

I forgot to add refresh the page and clicking out after saving the heart isn't purple.

Also on your About option page on the extension, it has 2020, Just thought I would share for a good plugin!

**Comment by sixcious** [comment] 2023-10-26 19:39
Hi again, thanks for the video!

OK, so I see two issues:

1. After you clicked the `YES` Button in the Save Dialog, you didn't click the `ACCEPT` Button at the bottom and instead you clicked out to exit the Popup UI Window. You need to click both `YES`, then `ACCEPT`; you can't close and reopen the Popup UI Window inbetween those two clicks.

2. You saved the URL pattern for only the current URL (changing the 2 to a 3), but you should make sure that your Saved URL pattern is more generic and doesn't contain a page number, or else it won't activate on any other URLs (such as page 4, page 5, and so on). This can easily be done by trimming off the last part of the URL, like for example: `https://download.cnet.com/windows`. You may even be able to remove the `/windows` part as well so it works for other platforms/search terms.

Both of these points are mentioned in the Save Dialog helper text (in case you ever forget). I made Point 1 in red text so it's hard to miss.

Yes, the 2020 is intentional and just my [preference](https://stackoverflow.com/a/2391555/988713), and also because that's the original year that the app was first released publicly. Thank you for the concern regardless.

I hope this helps! 💜

**Comment by eduardorandom** [comment] 2023-10-27 05:12
Hi.

So it worked.

1) What happened is more gamer logic. When saving a game, it has the save option aka purple heart. It has a popup if you want to or not aka yes or no options. So I expected it to be saved but it needs another option of the Accept button which sounds off from my gaming mind. Expecting another popup to agree and not that agree there. It's all gamer logic on my side so sorry about that.

2) Thanks for the advice but I'm just a beginner in the url part. Xpath does help!

Regarding the save steps, I can make a short video or maybe gif to give a better demonstration and you can link it in the wiki so other people don't make mistakes if you don't mind.

**Comment by sixcious** [comment] 2023-10-27 18:01
Hi, no worries on the video! I'm glad you've got it working. I'll go ahead and close this.

Thank you!

**Closed by sixcious** 2023-10-27 18:01 UTC
Labels: question
